name: AthoraCore
main: AthoraCore.main.Main
version: "1.0.0"
api: ["1.0.11"]
author: Benny
description: Athora Core Plugin
#commands:
#  athoracore:
#    description: "Verändere Werte im Core System direkt im Spiel!"
#    permission: "athora.core.api.commands"
#    permission-message: "Du hast keine Berechtigung den Befehl auszuführen!"